import { readdir } from "node:fs/promises";
import { join } from "node:path";
import { execCapture } from "../../shared/execCommand.js";

export interface XcodeProjectRef {
  /** Path to pass to `xcodebuild -workspace` or `-project`. */
  path: string;
  isWorkspace: boolean;
  scheme: string;
}

/** Finds the generated iOS workspace/project (post `expo prebuild` or a bare RN project) and its default scheme. */
export async function findXcodeProject(iosDir: string): Promise<XcodeProjectRef> {
  const entries = await readdir(iosDir);
  const workspace = entries.find((name) => name.endsWith(".xcworkspace"));
  const project = entries.find((name) => name.endsWith(".xcodeproj"));
  const target = workspace ?? project;
  if (!target) throw new Error(`No .xcworkspace or .xcodeproj found in ${iosDir}`);

  const isWorkspace = target.endsWith(".xcworkspace");
  const path = join(iosDir, target);
  const listOutput = await execCapture(
    "xcodebuild",
    [isWorkspace ? "-workspace" : "-project", path, "-list"],
    iosDir,
  );
  const targetName = target.replace(/\.(xcworkspace|xcodeproj)$/, "");
  const scheme = pickScheme(listOutput, targetName);
  return { path, isWorkspace, scheme };
}

/**
 * A workspace generated by CocoaPods lists every Pod's own autocreated scheme
 * alongside the app's — picking the first one alphabetically (as this used to)
 * can land on a Pod (e.g. "EXApplication") instead of the app itself. The app's
 * scheme name matches the workspace/project's own basename, so prefer that.
 */
function pickScheme(xcodebuildListOutput: string, targetName: string): string {
  const lines = xcodebuildListOutput.split("\n");
  const schemesIndex = lines.findIndex((line) => line.trim() === "Schemes:");
  if (schemesIndex === -1) throw new Error("Could not find a scheme via `xcodebuild -list`");
  const schemes = lines.slice(schemesIndex + 1).map((line) => line.trim()).filter((line) => line.length > 0);
  if (schemes.length === 0) throw new Error("`xcodebuild -list` reported no schemes");
  return schemes.find((scheme) => scheme === targetName) ?? schemes[0];
}
